In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [2]:
my_list = [1,2,3,4,5]
type(my_list)

list

In [3]:
# Creating a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
# Creating a 2-dimensional array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [6]:
# Creating a 3-dimensional array
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
import numpy as np

# Creating a 1-dimensional array
arr = np.array([10, 20, 30, 40, 50])

# Attributes
print("Array:", arr)
print("Shape:", arr.shape)           # Tuple of array dimensions
print("Number of Dimensions:", arr.ndim)  # Number of axes (dimensions)
print("Data Type:", arr.dtype)       # Data type of elements
print("Size:", arr.size)             # Total number of elements
print("Type:", type(arr))            # Type of the object (should be <class 'numpy.ndarray'>)


Array: [10 20 30 40 50]
Shape: (5,)
Number of Dimensions: 1
Data Type: int64
Size: 5
Type: <class 'numpy.ndarray'>


In [8]:
import numpy as np

# Creating a 2-dimensional array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Attributes
print("Array:\n", arr_2d)
print("Shape:", arr_2d.shape)         # (rows, columns)
print("Number of Dimensions:", arr_2d.ndim)  # 2
print("Data Type:", arr_2d.dtype)     # e.g., int64 or int32
print("Size:", arr_2d.size)           # Total number of elements
print("Type:", type(arr_2d))          # <class 'numpy.ndarray'>


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Data Type: int64
Size: 6
Type: <class 'numpy.ndarray'>


In [9]:
import numpy as np

# Creating a 3-dimensional array
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

# Attributes
print("Array:\n", arr_3d)
print("Shape:", arr_3d.shape)         # (depth, rows, columns)
print("Number of Dimensions:", arr_3d.ndim)  # 3
print("Data Type:", arr_3d.dtype)     # e.g., int64
print("Size:", arr_3d.size)           # Total number of elements
print("Type:", type(arr_3d))          # <class 'numpy.ndarray'>


Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Number of Dimensions: 3
Data Type: int64
Size: 8
Type: <class 'numpy.ndarray'>


In [10]:
import numpy as np
import pandas as pd

# 2-dimensional NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a DataFrame from the array
df = pd.DataFrame(arr_2d, columns=['A', 'B', 'C'])  # Optional: add column names

# Display the DataFrame
print(df)


   A  B  C
0  1  2  3
1  4  5  6


In [11]:
# Create an array of shape (10, 2) with only ones
import numpy as np

# Create an array of shape (10, 2) filled with ones
ones_array = np.ones((10, 2))

print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7, 2,3))

print(zeros_array)



[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [14]:
# Create an array within a range of 0 and 100 with step 3
import numpy as np

# Create array from 0 to 100 with step 3
range_array = np.arange(0, 100, 3)

print(range_array)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
import numpy as np

# Create random integer array with values from 0 to 9 (10 excluded)
random_array = np.random.randint(0, 10, size=(7, 2))

print(random_array)


[[7 9]
 [4 4]
 [2 3]
 [6 1]
 [0 9]
 [5 9]
 [4 8]]


In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
import numpy as np

# Create random float array between 0 and 1 with shape (3, 5)
random_floats = np.random.rand(3, 5)

print(random_floats)


[[0.19387086 0.94811291 0.6494416  0.2592758  0.20813845]
 [0.01821639 0.18991406 0.48308399 0.75403908 0.49953455]
 [0.19951771 0.04355249 0.33088814 0.40721127 0.04447314]]


In [20]:
import numpy as np

np.random.seed(42)
random_array = np.random.rand(3, 5)

print(random_array)


[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]]


In [21]:
# Create a random array of numbers between 0 & 10 of size (4, 6)
#float
import numpy as np

# Random float array between 0 and 10, shape (4, 6)
random_floats = np.random.uniform(0, 10, size=(4, 6))

print(random_floats)


[[1.8340451  3.04242243 5.24756432 4.31945019 2.9122914  6.11852895]
 [1.39493861 2.92144649 3.66361843 4.56069984 7.85175961 1.99673782]
 [5.14234438 5.92414569 0.46450413 6.07544852 1.70524124 0.65051593]
 [9.48885537 9.65632033 8.08397348 3.04613769 0.97672114 6.84233027]]


In [22]:
#integer
import numpy as np

# Random integer array between 0 and 9 (10 is excluded), shape (4, 6)
random_integers = np.random.randint(0, 10, size=(4, 6))

print(random_integers)


[[6 7 2 0 3 1]
 [7 3 1 5 5 9]
 [3 5 1 9 1 9]
 [3 7 6 8 7 4]]


In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
import numpy as np

# Create and save the array
random_int_array = np.random.randint(1, 11, size=(3, 7))

print(random_int_array)


[[ 2  5  8 10  9  9  1]
 [ 9  7  9  8  1  8  8]
 [ 3  1  8  3  3  1  5]]


In [25]:
#Find the unique numbers in the array you just created
import numpy as np

# Example: array of random integers between 1 and 10
random_int_array = np.random.randint(1, 11, size=(3, 7))

# Find unique numbers
unique_numbers = np.unique(random_int_array)

print("Original array:\n", random_int_array)
print("Unique numbers:", unique_numbers)


Original array:
 [[ 1  5 10  7  7  9 10]
 [10  3  7  1  4  4  5]
 [ 7  7  4  7  3  6  2]]
Unique numbers: [ 1  2  3  4  5  6  7  9 10]


In [26]:
# Get the 0th index (first row)
first_row = random_int_array[0]

print("0th index (first row):", first_row)


0th index (first row): [ 1  5 10  7  7  9 10]


In [27]:
# Get the first 2 rows
first_two_rows = random_int_array[:2]

print("First 2 rows:\n", first_two_rows)


First 2 rows:
 [[ 1  5 10  7  7  9 10]
 [10  3  7  1  4  4  5]]


In [28]:
import numpy as np

# Random float array between 0 and 10
random_array = np.random.uniform(0, 10, size=(3, 5))

# Array of ones
ones_array = np.ones((3, 5))

# Print both arrays
print("Random Array:\n", random_array)
print("\nArray of Ones:\n", ones_array)


Random Array:
 [[6.24354048e+00 2.95633686e+00 1.05494260e+00 4.56534570e+00
  2.18440437e+00]
 [4.16509948e+00 8.83280259e+00 3.24345021e+00 1.22087955e+00
  3.56297838e+00]
 [9.06828442e+00 2.72132249e+00 6.47690121e+00 5.20376995e-03
  3.52568856e+00]]

Array of Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
# Add the two arrays
sum_array = random_array + ones_array

print("Sum of random_array and ones_array:\n", sum_array)


Sum of random_array and ones_array:
 [[ 7.24354048  3.95633686  2.0549426   5.5653457   3.18440437]
 [ 5.16509948  9.83280259  4.24345021  2.22087955  4.56297838]
 [10.06828442  3.72132249  7.47690121  1.00520377  4.52568856]]


In [30]:
import numpy as np

ones_array_5_3 = np.ones((5, 3))

print(ones_array_5_3)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
sum_array = ones_array + ones_array_5_3.T
print(sum_array)


[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [32]:
import numpy as np

another_ones_array = np.ones((3, 5))

print(another_ones_array)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
#Subtract the new array of ones from the other most recent array
result_array = random_array - another_ones_array

print("Result of subtraction:\n", result_array)


Result of subtraction:
 [[ 5.24354048  1.95633686  0.0549426   3.5653457   1.18440437]
 [ 3.16509948  7.83280259  2.24345021  0.22087955  2.56297838]
 [ 8.06828442  1.72132249  5.47690121 -0.99479623  2.52568856]]


In [34]:
matrix_product = np.dot(another_ones_array, random_array.T)  # or another_ones_array @ random_array.T
print(matrix_product)


[[17.00457002 21.02521021 21.79740045]
 [17.00457002 21.02521021 21.79740045]
 [17.00457002 21.02521021 21.79740045]]


In [35]:
squared_array = random_array ** 2

print("Array raised to the power of 2:\n", squared_array)


Array raised to the power of 2:
 [[3.89817977e+01 8.73992762e+00 1.11290389e+00 2.08423814e+01
  4.77162246e+00]
 [1.73480537e+01 7.80184016e+01 1.05199693e+01 1.49054687e+00
  1.26948149e+01]
 [8.22337822e+01 7.40559612e+00 4.19502492e+01 2.70792217e-05
  1.24304798e+01]]


In [36]:
import numpy as np

squared_array = np.square(random_array)

print("Array squared using np.square():\n", squared_array)


Array squared using np.square():
 [[3.89817977e+01 8.73992762e+00 1.11290389e+00 2.08423814e+01
  4.77162246e+00]
 [1.73480537e+01 7.80184016e+01 1.05199693e+01 1.49054687e+00
  1.26948149e+01]
 [8.22337822e+01 7.40559612e+00 4.19502492e+01 2.70792217e-05
  1.24304798e+01]]


In [37]:
import numpy as np

mean_value = np.mean(random_array)

print("Mean of the array:", mean_value)


Mean of the array: 3.9884787112499427


In [38]:
import numpy as np

max_value = np.max(random_array)

print("Maximum value in the array:", max_value)



Maximum value in the array: 9.06828441545754


In [39]:
import numpy as np

min_value = np.min(random_array)

print("Minimum value in the array:", min_value)


Minimum value in the array: 0.005203769953158188


In [2]:
#Find the standard deviation of the latest array
import numpy as np
random_array = np.random.uniform(0, 10, size=(3, 5))

std_dev = np.std(random_array)

print("Standard deviation of the array:", std_dev)


Standard deviation of the array: 2.830132145747698


In [3]:
# Find the variance of the latest array
import numpy as np

variance = np.var(random_array)

print("Variance of the array:", variance)


Variance of the array: 8.00964796239447


In [7]:
# Reshape the latest array to (3, 5, 1)
import numpy as np

array = np.random.rand(3,5)
random_array = array.reshape((3, 5, 1))
print(random_array)


[[[0.09510484]
  [0.18355818]
  [0.47464956]
  [0.22047959]
  [0.62591495]]

 [[0.57402924]
  [0.97806034]
  [0.38589969]
  [0.31267918]
  [0.49758992]]

 [[0.0060494 ]
  [0.86212212]
  [0.90694625]
  [0.29459349]
  [0.14425713]]]


In [9]:
# Transpose the latest array
import numpy as np

# Example array of shape (3, 5, 1)
array = np.arange(15).reshape(3, 5, 1)

# Transpose the array - specify the axes order
transposed_array = array.transpose(1, 0, 2)
print(transposed_array)

[[[ 0]
  [ 5]
  [10]]

 [[ 1]
  [ 6]
  [11]]

 [[ 2]
  [ 7]
  [12]]

 [[ 3]
  [ 8]
  [13]]

 [[ 4]
  [ 9]
  [14]]]


In [10]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
import numpy as np

# Set seed for reproducibility (optional)
np.random.seed(0)

# First array of size (3, 3)
array1 = np.random.randint(0, 11, size=(3, 3))

# Second array of size (3, 2)
array2 = np.random.randint(0, 11, size=(3, 2))

print("Array 1 (3x3):")
print(array1)

print("\nArray 2 (3x2):")
print(array2)


Array 1 (3x3):
[[5 0 3]
 [3 7 9]
 [3 5 2]]

Array 2 (3x2):
[[ 4  7]
 [ 6  8]
 [ 8 10]]


In [11]:
# Perform a dot product on the two newest arrays you created
import numpy as np

# Assuming array1 and array2 are defined as above
result = np.dot(array1, array2)
# Or equivalently: result = array1 @ array2

print("Dot product result (shape should be 3x2):")
print(result)


Dot product result (shape should be 3x2):
[[ 44  65]
 [126 167]
 [ 58  81]]


In [12]:
#Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
import numpy as np

# Example arrays that would yield a 3x2 result
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])  # shape: (3, 3)

array2 = np.array([[1, 0],
                   [0, 1],
                   [1, 1]])      # shape: (3, 2)

# Perform the dot product
result = np.dot(array1, array2)

print("Dot product result (shape should be 3x2):")
print(result)


Dot product result (shape should be 3x2):
[[ 4  5]
 [10 11]
 [16 17]]


In [13]:
import numpy as np

# Set a shape, e.g., 3x3
shape = (3, 3)

# Create two arrays of random integers between 0 and 10
array1 = np.random.randint(0, 11, size=shape)
array2 = np.random.randint(0, 11, size=shape)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)


Array 1:
[[1 6 7]
 [7 8 1]
 [5 9 8]]

Array 2:
[[9 4 3]
 [0 3 5]
 [0 2 3]]


In [14]:
# Compare the two arrays with '>'
comparison = array1 > array2

print("Comparison result (array1 > array2):")
print(comparison)


Comparison result (array1 > array2):
[[False  True  True]
 [ True  True False]
 [ True  True  True]]


In [15]:
# Compare the two arrays with '>='
comparison = array1 >= array2

print("Comparison result (array1 >= array2):")
print(comparison)


Comparison result (array1 >= array2):
[[False  True  True]
 [ True  True False]
 [ True  True  True]]


In [16]:
# Find which elements of the first array are greater than 7
greater_than_7 = array1 > 7

print("Elements of array1 greater than 7 (as a Boolean mask):")
print(greater_than_7)


Elements of array1 greater than 7 (as a Boolean mask):
[[False False False]
 [False  True False]
 [False  True  True]]


In [17]:
# Which parts of each array are equal? (try using '==')
equal_elements = array1 == array2

print("Elements where array1 and array2 are equal (Boolean mask):")
print(equal_elements)


Elements where array1 and array2 are equal (Boolean mask):
[[False False False]
 [False False False]
 [False False False]]


In [18]:
# Sort one of the arrays you just created in ascending order
# Sort each column in ascending order
sorted_cols = np.sort(array1, axis=0)
print("Array1 sorted along columns:")
print(sorted_cols)


Array1 sorted along columns:
[[1 6 1]
 [5 8 7]
 [7 9 8]]


In [19]:
# Sort the indexes of one of the arrays you just created
# Sorted indices along each row
sorted_indices_rows = np.argsort(array1, axis=1)
print("Indices that would sort array1 along each row:")
print(sorted_indices_rows)

# Sorted indices along each column
sorted_indices_cols = np.argsort(array1, axis=0)
print("Indices that would sort array1 along each column:")
print(sorted_indices_cols)



Indices that would sort array1 along each row:
[[0 1 2]
 [2 0 1]
 [0 2 1]]
Indices that would sort array1 along each column:
[[0 0 1]
 [2 1 0]
 [1 2 2]]


In [21]:
# Find the index with the maximum value in one of the arrays you've created
max_index_flat = np.argmax(array1)
print("Index of maximum value in array1 (flattened):", max_index_flat)


Index of maximum value in array1 (flattened): 7


In [22]:
max_index_multi = np.unravel_index(max_index_flat, array1.shape)
print("Index of maximum value in array1 (multi-dimensional):", max_index_multi)


Index of maximum value in array1 (multi-dimensional): (np.int64(2), np.int64(1))


In [23]:
# Find the index with the minimum value in one of the arrays you've created
min_index_flat = np.argmin(array1)
print("Index of minimum value in array1 (flattened):", min_index_flat)

# Convert flattened index to multi-dimensional index
min_index_multi = np.unravel_index(min_index_flat, array1.shape)
print("Index of minimum value in array1 (multi-dimensional):", min_index_multi)


Index of minimum value in array1 (flattened): 0
Index of minimum value in array1 (multi-dimensional): (np.int64(0), np.int64(0))


In [24]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indices_axis1 = np.argmax(array1, axis=1)

print("Indexes of max values along axis=1 (per row) in array1:")
print(max_indices_axis1)


Indexes of max values along axis=1 (per row) in array1:
[2 1 1]


In [25]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indices_axis0 = np.argmin(array1, axis=0)

print("Indexes of min values along axis=0 (per column) in array1:")
print(min_indices_axis0)



Indexes of min values along axis=0 (per column) in array1:
[0 0 1]


In [26]:
# Create an array of normally distributed random numbers
import numpy as np

# Parameters for the normal distribution
mean = 0        # mean of the distribution
std_dev = 1     # standard deviation
shape = (3, 3)  # shape of the output array

# Generate the array
normal_array = np.random.normal(loc=mean, scale=std_dev, size=shape)

print("Array of normally distributed random numbers:")
print(normal_array)


Array of normally distributed random numbers:
[[-0.18158257  1.41020463 -0.37447169]
 [ 0.27519832 -0.96075461  0.37692697]
 [ 0.03343893  0.68056724 -1.56349669]]


In [27]:
# Create an array with 10 evenly spaced numbers between 1 and 100
import numpy as np

evenly_spaced = np.linspace(1, 100, 10)

print("10 evenly spaced numbers between 1 and 100:")
print(evenly_spaced)


10 evenly spaced numbers between 1 and 100:
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
